### ISSUE TITLE
New attribures are not highlited in diff

### ISSUE THREAD

**Issue by PavelSerogodsky** [yoep/xsd-compare#6]
![image](https://user-images.githubusercontent.com/61416249/75152728-c5f2a080-571a-11ea-9684-535495d90e6f.png)

**Comment by yoep** [comment]
Issue should be resolved on the latest version on the develop branch

![image](https://user-images.githubusercontent.com/567495/76160749-0b589a00-612d-11ea-967c-4bdc9fb5ba65.png)
![image](https://user-images.githubusercontent.com/567495/76160757-23301e00-612d-11ea-9aa4-3c4f7bd51c18.png)

**Comment by yoep** [comment]
Issue has been fixed in release in 0.0.6
