### ISSUE TITLE
How to start xsd-compare?

### ISSUE THREAD

**Issue by Henrich-BGRCI** [yoep/xsd-compare#7]
How do I start the program xsd-compare on Windows 10? What are the requirements? 
I tried to run "javac XsdCompareConfiguration.java" or "javac XsdCompareApplication.java" using jdk-14, but I got a lot of errors (e.g. package com.fasterxml.jackson.databind does not exist).
Thanks for helping!

**Comment by yoep** [comment]
Hi 

If you want to just run the application without any modifications, you can download the latest executables for windows here: https://github.com/yoep/xsd-compare/releases/tag/0.0.6

If you want to modify the application and build it, you need to use `JDK 8` as the application uses `com.sun.org.apache.xerces.internal` which is not accessible as of `JDK 9+`. 
I'm still searching for a solution to upgrade to the latest JDK but couldn't find any at the moment as there is no library that provides XSD file details (which is currently provided by Apache Xerces internal).

**Comment by Henrich-BGRCI** [comment]
Thanks for the download link. 
After installation (choosing language and accepting the license) nothing happens if I start the xsd-compare.exe. Also the windows-standalone version does not do anything. 
Using java-se-8u41-ri (https://jdk.java.net/java-se-ri/8-MR3) gives errors (package com.github.spring.boot.javafx does not exist ...).

**Comment by yoep** [comment]
I've tested the windows standalone version on another windows machine that didn't had any Java version installed and it worked correctly on that one, so I currently don't have any indication of what might be going wrong on your machine.

I did however attach the fat jar to the 0.0.6 release: [xsd-compare_0.0.6.jar](https://github.com/yoep/xsd-compare/releases/download/0.0.6/xsd-compare_0.0.6.jar).
Can you download it and run it through CMD with JRE/JDK 8?

**Comment by Henrich-BGRCI** [comment]
Since Oracle JDK License has changed, I cannot use it anymore for free for business purpose.
Anyway, shortly after running your program I got a trojan warning, but I could not figure out if it is related to it or just a false positive warning.
